#!/bin/bash
##############################
# Exports:
# - jr_funct_git_feature_create
#   @see jr_funct_git_feature_create
##############################

alias jr_doc_funct_git_feature_create="echo \"
##########
# Creates a new branch
#
# @param1 name of the feature
##########\""
jr_funct_git_feature_create(){
    local featureToCreate="${1}"
    
    git checkout -b "${featureToCreate}" develop || (echo ">>> Could not create branch."; exit 1)
    git push --no-verify --set-upstream origin "${featureToCreate}"
}
export -f jr_funct_git_feature_create