#!/bin/bash
##############################
# Exports:
# - jr_funct_git_feature_create
#   @see jr_funct_git_feature_create
### - jr_funct_git_finish_release
###   @see jr_funct_git_finish_release
##############################

alias jr_doc_funct_git_feature_create="echo \"
##########
# Creates a new branch
#
# @param1 name of the feature
##########\""
jr_funct_git_feature_create(){
    local featureToCreate="${1}"
    
    git checkout -b "${featureToCreate}" develop || (echo ">>> Could not create branch."; exit 1)
    git push --no-verify --set-upstream origin "${featureToCreate}"
}
export -f jr_funct_git_feature_create



#alias jr_doc_funct_git_finish_release="echo \"
###########
## Finishes a release
##
## @param1 name of the release to finish
###########\""
#jr_funct_git_finish_release(){
#    local releaseToFinish="${1}"
#    
#    git checkout master && git merge --no-ff "release-${releaseToFinish}" || { echo ">>> FAILED to merge release into master"; exit 1; }
#     
#    git tag -a "${releaseToFinish}" -m "For changes see [${releaseToFinish}] section in CHANGELOG.md" && git push && git push --tags || { echo ">>> FAILED to create tag"; exit 1; }
#      
#    git checkout develop && git merge --no-ff "release-${releaseToFinish}" && git push || { echo ">>> FAILED to merge release into develop"; exit 1; }
#    
#    git push --no-verify origin --delete "release-${releaseToFinish}" && git branch -d "release-${releaseToFinish}" || { echo ">>> FAILED to remove release branch"; exit 1; }
#}
#export -f jr_funct_git_finish_release