#!/bin/bash
##############################
# Exports:
# - jr_funct_git_create_feature
#   @see jr_doc_funct_git_create_feature
##############################

alias jr_doc_funct_git_create_feature="echo \"
##########
# Creates a new branch
#
# @param1 name of the feature
##########\""
jr_funct_git_create_feature(){
    local featureToCreate="${1}"
    
    git checkout -b "${featureToCreate}" develop
    git push --no-verify --set-upstream origin "${featureToCreate}"
}
export -f jr_funct_git_create_feature