#!/bin/bash
##############################
# Exports:
# - jr_funct_list_files_containing
#   @see jr_doc_funct_list_files_containing
##############################



alias jr_doc_funct_list_files_containing="echo \"$(cat <<'//'
##########
# Lists all files that contain a regex.
#
# @param1 a path to a directory in which should be searched.
# @param2 a regex.
# @stdout a list of files that contain the regex.
##########
//
)\""
jr_funct_list_files_containing(){
    local searchDirectory="${1}"
    local regex="${2}"
    grep --dereference-recursive --line-number --extended-regexp "${regex}" "${searchDirectory}"
}
export -f jr_funct_list_files_containing